routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('soulmate' , 'SoulmatesController');
Route::get('/','SoulmatesController@index');
Route::get('/search','SoulmatesController@search');

app/Soulmate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Soulmate extends Model
{
    protected $fillable = [
      'first_name', 'last_name', 'image'

    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/SoulmatesController.php
<?php

namespace App\Http\Controllers;
use App\Soulmate;

use Illuminate\Http\Request;

class SoulmatesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $data = Soulmate::orderBy('id','desc')->paginate(8);
        return  view('index',['data' => $data]);


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    public function search(Request $request)
    {

        $searchkey = \Request::get('search');
        $data = Soulmate::where('first_name','like','%' .$searchkey. '%')
            ->orderBy('id')->paginate(8);
        return view('index',['data' => $data]);


    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'first_name' => 'required',
            'last_name'  =>  'required',
            'image'     =>  'required|image|max:2048'

        ]);


        $image = $request->file('image');

        $new_name = rand() . '.' . $image->getClientOriginalExtension();
        $image->move(public_path('images'), $new_name);
        $form_data = array(
            'first_name'  => $request->first_name,
            'last_name'  => $request->last_name,
            'image'   => $new_name

        );
        Soulmate::create($form_data);

        return redirect('soulmate')->with('success', 'Data Added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Soulmate::findOrFail($id);
        return view('view', compact('data'));





    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Soulmate::findOrfail($id);
        return view('edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $image_name = $request->hidden_image;
        $image = $request->file('image');
        if ($image != '')
        {
           $request->validate([
              'first_name' => 'required',
              'last_name' => 'required',
               'image' => 'image|max:2048'
           ]);
           $image_name = rand() . '.' . $image->getClientOriginalExtension();
           $image->move(public_path('images'), $image_name);
        }
        else
            {
            $request->validate([
                'first_name' => 'required',
                'last_name' => 'required',
                'image' => 'image|max:2048'
            ]);
        }
        $form_data = array(
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'image' => $image_name
        );
        Soulmate::whereId($id)->update($form_data);
        return redirect('soulmate')->with('success', 'Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Soulmate::findOrFail($id);
        $data->delete();
        return redirect('soulmate')->with('success', 'Data is successfully deleted');
    }
}

resources/views/create.blade.php
@extends('parent')

@section('main')
    @if($errors->any())
        <div class="alert alert-warning">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div align="right">
        <a href="{{ route('soulmate.index') }}" class="btn btn-default">Back</a>
    </div>

    <form method="post" action="{{ route('soulmate.store') }}" enctype="multipart/form-data">

        @csrf
        <div class="form-group">
            <label class="col-md-4 text-right">Enter Pet Name</label>
            <div class="col-md-8">
                <input type="text" name="first_name" class="form-control input-lg" />
            </div>
        </div>
        <br />
        <br />
        <br />
        <div class="form-group">
            <label class="col-md-4 text-right">Enter Detail</label>
            <div class="col-md-8">
                <input type="text" name="last_name" class="form-control input-lg" />
            </div>
        </div>
        <br />
        <br />
        <br />
        <div class="form-group">
            <label class="col-md-4 text-right">Select Profile Image</label>
            <div class="col-md-8">
                <input type="file" name="image" />
            </div>
        </div>
        <br /><br /><br />
        <div class="form-group text-center">
            <input type="submit" name="add" class="btn btn-primary btn-lg input-lg" value="Add Data" />
        </div>

    </form>

@endsection

resources/views/edit.blade.php
@extends('parent')

@section('main')

    @if ($errors->any())
        <div class="alert alert-warning">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div align="right">
        <a href="{{ route('soulmate.index') }}" class="btn btn-default">Back</a>
    </div>
    <br />
    <form method="post" action="{{ route('soulmate.update', $data->id) }}" enctype="multipart/form-data">

        @csrf
        @method('PATCH')
        <div class="form-group">
            <label class="col-md-4 text-right">Enter Pet Name</label>
            <div class="col-md-8">
                <input type="text" name="first_name" value="{{ $data->first_name }}" class="form-control input-lg" />
            </div>
        </div>
        <br />
        <br />
        <br />
        <div class="form-group">
            <label class="col-md-4 text-right">Enter Detail</label>
            <div class="col-md-8">
                <input type="text" name="last_name" value="{{ $data->last_name }}" class="form-control input-lg" />
            </div>
        </div>
        <br />
        <br />
        <br />
        <div class="form-group">
            <label class="col-md-4 text-right">Select Profile Image</label>
            <div class="col-md-8">
                <input type="file" name="image" />
                <img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-thumbnail" width="100" />
                <input type="hidden" name="hidden_image" value="{{ $data->image }}" />
            </div>
        </div>
        <br /><br /><br />
        <div class="form-group text-center">
            <input type="submit" name="edit" class="btn btn-warning btn-lg input-lg" value="Edit Data" />
        </div>
    </form>

@endsection

resources/views/index.blade.php
@extends('parent')

@section('main')


{{--    *********--}}

<div class="row">
<div class="col-md-6">
{{--<h1>SOULMATE PETS</h1>--}}
</div>
 <div class="col-md-4">
     <form action="{{url("/search")}}"method="get">
         <div class="input-group-mb3">
             <input type="search" name="search" class="form-control" placeholder="search...">
             <span  class="input-group-append">
                 <button  style="margin-top:  -3.4rem; margin-left: 35rem;"   type="submit" class="btn btn-success">Search</button>
             </span>
         </div>
        </form>
     </div>
         {{-----------}}

    <div class="col-md-2 text-right">

        <a href="{{ route('soulmate.create') }}" class="btn btn-primary ">Add</a>

    </div>




</div>
{{--row--}}

@if($message =  Session::get('success'))
    <div class="alert alert-info">
        <p>{{ $message }}</p>
    </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th width="10%">Profile</th>
            <th width="35%">Name</th>
            <th width="35%">Detail</th>
            <th width="30%">Action</th>
        </tr>
        @foreach($data as $row)
            <tr>
                <td><img src="{{ URL::to('/') }}/images/{{ $row->image }}" class="img-thumbnail" width="75" /></td>
                <td>{{ $row->first_name }}</td>
                <td>{{ $row->last_name }}</td>
                <td>

                    <form action="{{ route('soulmate.destroy', $row->id) }}"
                          method="post">
                  <a href="{{ route('soulmate.show', $row->id) }}" class="btn btn-info" >Select</a>
                    <a href="{{ route('soulmate.edit', $row->id) }}" class="btn btn-warning">Edit</a>


                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger ">Delete</button>
                    </form>



                </td>
            </tr>
        @endforeach
    </table>





    {!! $data->links() !!}
@endsection

resources/views/parent.blade.php
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Soulmate Pets</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1' name='viewport'/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
    <img width="100%" src="<?php echo asset('assets/img/banner3.jpg'); ?>">
    <link rel="stylesheet" type="text/css" href="<?php echo asset('assets/css/style.css'); ?>">
</head>
<body>
<div class="container">
    <br />
    <h1 class="text-danger" align="center">SOULMATE PETS</h1>
    <br />
    @yield('main')

</div>
<div class="footer">
    <img width="100%" src="<?php echo asset('assets/img/footer3-01.jpg'); ?>">
</div>
</body>
</html>

resources/views/view.blade.php
@extends('parent')

@section('main')

    <div class="jumbotron text-center">
        <div align="right">
            <a href="{{ route('soulmate.index') }}" class="btn btn-default">Back</a>
        </div>
        <br />
        <img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-thumbnail" />
        <h3>Pet Name - {{ $data->first_name }} </h3>
        <h3>Detail - {{ $data->last_name }}</h3>


    </div>
@endsection